### Cleaning Job Vacancy

In [1]:
import numpy as np
import pandas as pd

In [2]:
files = 'C:/Users/yiran/Google Drive/2018 S1/Cleaning Data/Material Data/Job vacancy/Job vacancy cleaning.xlsx'
occupations_sheet = pd.ExcelFile(files)
jobvac = occupations_sheet.parse('Sheet1')

In [3]:
jobvac.head(5)

,OCCUPATIONS,STATES,2006-03-01 00:00:00,2006-04-01 00:00:00,2006-05-01 00:00:00,2006-06-01 00:00:00,2006-07-01 00:00:00,2006-08-01 00:00:00,2006-09-01 00:00:00,2006-10-01 00:00:00,...,2017-05-01 00:00:00,2017-06-01 00:00:00,2017-07-01 00:00:00,2017-08-01 00:00:00,2017-09-01 00:00:00,2017-10-01 00:00:00,2017-11-01 00:00:00,2017-12-01 00:00:00,2018-01-01 00:00:00,2018-02-01 00:00:00
0,Australia Total,AUST,214669,213341,222176,223386,233722,240445,240671,254445,...,171808,170120,179821,181896,185663,191075,185991,163264,161651,163169
1,Chief Executives and Managing Directors,AUST,158.85,160.57,180.53,207.43,214.49,212.53,197.01,216.38,...,309.33,322,337.67,329.33,339.67,345.33,359.33,298.67,302.33,277.67
2,General Managers,AUST,308.89,308.42,319.94,311.29,307.56,300.73,293.66,317.57,...,494.33,481.33,475,447.67,434.67,461.67,455.67,429,447.67,469
3,Legislators,AUST,.,.,.,.,.,.,.,.,...,.,.,.,.,.,.,.,.,.,.
4,Aquaculture Farmers,AUST,0.67,1.33,1.33,1.33,0.67,1.33,2,2.33,...,0.33,0.33,0.67,1,0.67,0.33,0.33,0.67,1.33,1

In [4]:
len(jobvac)

3231

In [5]:
jobvac01 = jobvac[jobvac.STATES == "AUST"]

In [6]:
jobvac01.STATES.unique()

array([u'AUST'], dtype=object)

Correctly excluded AUST data.

In [7]:
jobvac01.head(5)

,OCCUPATIONS,STATES,2006-03-01 00:00:00,2006-04-01 00:00:00,2006-05-01 00:00:00,2006-06-01 00:00:00,2006-07-01 00:00:00,2006-08-01 00:00:00,2006-09-01 00:00:00,2006-10-01 00:00:00,...,2017-05-01 00:00:00,2017-06-01 00:00:00,2017-07-01 00:00:00,2017-08-01 00:00:00,2017-09-01 00:00:00,2017-10-01 00:00:00,2017-11-01 00:00:00,2017-12-01 00:00:00,2018-01-01 00:00:00,2018-02-01 00:00:00
0,Australia Total,AUST,214669,213341,222176,223386,233722,240445,240671,254445,...,171808,170120,179821,181896,185663,191075,185991,163264,161651,163169
1,Chief Executives and Managing Directors,AUST,158.85,160.57,180.53,207.43,214.49,212.53,197.01,216.38,...,309.33,322,337.67,329.33,339.67,345.33,359.33,298.67,302.33,277.67
2,General Managers,AUST,308.89,308.42,319.94,311.29,307.56,300.73,293.66,317.57,...,494.33,481.33,475,447.67,434.67,461.67,455.67,429,447.67,469
3,Legislators,AUST,.,.,.,.,.,.,.,.,...,.,.,.,.,.,.,.,.,.,.
4,Aquaculture Farmers,AUST,0.67,1.33,1.33,1.33,0.67,1.33,2,2.33,...,0.33,0.33,0.67,1,0.67,0.33,0.33,0.67,1.33,1

In [8]:
len(jobvac01)

359

In [9]:
jobvac01.OCCUPATIONS = jobvac01.OCCUPATIONS.str.title()

C:\Users\yiran\Anaconda2\lib\site-packages\pandas\core\generic.py:2999: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[name] = value

In [10]:
jobvac01.head(5)

,OCCUPATIONS,STATES,2006-03-01 00:00:00,2006-04-01 00:00:00,2006-05-01 00:00:00,2006-06-01 00:00:00,2006-07-01 00:00:00,2006-08-01 00:00:00,2006-09-01 00:00:00,2006-10-01 00:00:00,...,2017-05-01 00:00:00,2017-06-01 00:00:00,2017-07-01 00:00:00,2017-08-01 00:00:00,2017-09-01 00:00:00,2017-10-01 00:00:00,2017-11-01 00:00:00,2017-12-01 00:00:00,2018-01-01 00:00:00,2018-02-01 00:00:00
0,Australia Total,AUST,214669,213341,222176,223386,233722,240445,240671,254445,...,171808,170120,179821,181896,185663,191075,185991,163264,161651,163169
1,Chief Executives And Managing Directors,AUST,158.85,160.57,180.53,207.43,214.49,212.53,197.01,216.38,...,309.33,322,337.67,329.33,339.67,345.33,359.33,298.67,302.33,277.67
2,General Managers,AUST,308.89,308.42,319.94,311.29,307.56,300.73,293.66,317.57,...,494.33,481.33,475,447.67,434.67,461.67,455.67,429,447.67,469
3,Legislators,AUST,.,.,.,.,.,.,.,.,...,.,.,.,.,.,.,.,.,.,.
4,Aquaculture Farmers,AUST,0.67,1.33,1.33,1.33,0.67,1.33,2,2.33,...,0.33,0.33,0.67,1,0.67,0.33,0.33,0.67,1.33,1

### Import ABS Final Occupation List

In [12]:
files = 'C:/Users/yiran/Google Drive/2018 S1/Cleaning Data/Material Data/ABS OCCUP LIST FINAL.xlsx'
sheet = pd.ExcelFile(files)
ABS_List = sheet.parse('Sheet1')

In [13]:
ABS_List.head(5)

                               OCCUPATIONS
0  Chief Executives And Managing Directors
1                         General Managers
2                              Legislators
3                             Crop Farmers
4                        Livestock Farmers

In [36]:
merged_jobvac01 = pd.merge(ABS_List, jobvac01, how = 'inner')

In [37]:
len(merged_jobvac01)

349

In [38]:
len(jobvac01)

359

In [39]:
len(ABS_List)

349

In [40]:
len(jobvac01.OCCUPATIONS.unique())

359

In [41]:
len(merged_jobvac01.OCCUPATIONS.unique())

349

In [42]:
orig_job = pd.DataFrame(jobvac01.OCCUPATIONS.unique())

In [43]:
len(orig_job)

359

In [44]:
orig_job.head(5)

                                         0
0                          Australia Total
1  Chief Executives And Managing Directors
2                         General Managers
3                              Legislators
4                      Aquaculture Farmers

In [45]:
orig_job = orig_job.rename(columns={0 : 'OCCUP'})

In [46]:
merged_job = pd.DataFrame(merged_jobvac01.OCCUPATIONS.unique())

In [47]:
len(merged_job)

349

In [48]:
merged_job.head(5)

                                         0
0  Chief Executives And Managing Directors
1                         General Managers
2                              Legislators
3                             Crop Farmers
4                        Livestock Farmers

In [49]:
merged_job = merged_job.rename(columns={0 : 'OCCUP'})

In [50]:
len(orig_job[~orig_job.OCCUP.isin(merged_job.OCCUP)])

10

In [51]:
orig_job[~orig_job.OCCUP.isin(merged_job.OCCUP)]

                                             OCCUP
0                                  Australia Total
4                              Aquaculture Farmers
7                 Mixed Crop And Livestock Farmers
26   Senior Non-Commissioned Defence Force Members
166                                Floor Finishers
183                                       Shearers
193                Canvas And Leather Goods Makers
201                                      Jewellers
224            Defence Force Members - Other Ranks
339                            Aquaculture Workers

In [52]:
ABS_List.OCCUPATIONS[~ABS_List.OCCUPATIONS.isin(merged_job.OCCUP)]

Series([], Name: OCCUPATIONS, dtype: object)

In [53]:
orig_job.iloc[92]

OCCUP    Middle School Teachers
Name: 92, dtype: object

### Check for same meaning occupation

In [32]:
jobvac01[jobvac01.OCCUPATIONS == 'Vocational Education Teachers (Aus) / Polytechnic Teachers (Nz)']

,OCCUPATIONS,STATES,2006-03-01 00:00:00,2006-04-01 00:00:00,2006-05-01 00:00:00,2006-06-01 00:00:00,2006-07-01 00:00:00,2006-08-01 00:00:00,2006-09-01 00:00:00,2006-10-01 00:00:00,...,2017-05-01 00:00:00,2017-06-01 00:00:00,2017-07-01 00:00:00,2017-08-01 00:00:00,2017-09-01 00:00:00,2017-10-01 00:00:00,2017-11-01 00:00:00,2017-12-01 00:00:00,2018-01-01 00:00:00,2018-02-01 00:00:00
96,Vocational Education Teachers (Aus) / Polytech...,AUST,25.17,23.17,27.13,30.82,34.84,33.22,33.27,38.25,...,26.33,26,26,23,23.33,28.67,32.33,28,20.67,18.33

In [33]:
jobvac01['OCCUPATIONS'] = jobvac01['OCCUPATIONS'].replace('Middle School Teachers (Aus) / Intermediate School Teachers (Nz)', 'Middle School Teachers')

C:\Users\yiran\Anaconda2\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [34]:
jobvac01['OCCUPATIONS'] = jobvac01['OCCUPATIONS'].replace('Vocational Education Teachers (Aus) / Polytechnic Teachers (Nz)', 'Vocational Education Teachers')

C:\Users\yiran\Anaconda2\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [35]:
jobvac01['OCCUPATIONS'] = jobvac01['OCCUPATIONS'].replace('Dietitians', 'Dieticians')

C:\Users\yiran\Anaconda2\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

### Final List of Job Vacancy Data

In [54]:
merged_jobvac01

,OCCUPATIONS,STATES,2006-03-01 00:00:00,2006-04-01 00:00:00,2006-05-01 00:00:00,2006-06-01 00:00:00,2006-07-01 00:00:00,2006-08-01 00:00:00,2006-09-01 00:00:00,2006-10-01 00:00:00,...,2017-05-01 00:00:00,2017-06-01 00:00:00,2017-07-01 00:00:00,2017-08-01 00:00:00,2017-09-01 00:00:00,2017-10-01 00:00:00,2017-11-01 00:00:00,2017-12-01 00:00:00,2018-01-01 00:00:00,2018-02-01 00:00:00
0,Chief Executives And Managing Directors,AUST,158.85,160.57,180.53,207.43,214.49,212.53,197.01,216.38,...,309.33,322,337.67,329.33,339.67,345.33,359.33,298.67,302.33,277.67
1,General Managers,AUST,308.89,308.42,319.94,311.29,307.56,300.73,293.66,317.57,...,494.33,481.33,475,447.67,434.67,461.67,455.67,429,447.67,469
2,Legislators,AUST,.,.,.,.,.,.,.,.,...,.,.,.,.,.,.,.,.,.,.
3,Crop Farmers,AUST,25.74,33.15,32.84,22.86,15.84,16.12,15.38,16.69,...,8.33,9.67,12.67,16,14.67,13,11,11.67,12.67,10.67
4,Livestock Farmers,AUST,35.17,33.55,35.91,34.55,33.84,31.17,34.5,37.24,...,33.33,32.33,32.67,33,34,35.33,33.67,27.33,25.67,27.33
5,Advertising And Sales Managers,AUST,6397.5,6416.68,6649.76,6778.27,7164.54,7196.82,6934.29,6895.75,...,6385,6314.33,6632.67,6724,6762,6759.33,6424,5594.67,5732.33,5932
6,Corporate Services Managers,AUST,543.76,558.66,583.52,590.18,619.45,632.9,583.82,576.61,...,628.33,615,630,652.33,661.67,652,619.33,558.67,586.67,601
7,Finance Managers,AUST,1059.56,1110.33,1226.24,1267.71,1280.85,1244.69,1191.25,1256.6,...,866.33,864,876.67,836.33,839,875,866,780,790.67,828.67
8,Human Resource Managers,AUST,460.86,468.55,511.6,525.16,535.28,538.09,506.91,532.67,...,471.33,469,524,524,536,515.33,488.33,420.67,479,495
9,Policy And Planning Managers,AUST,788.41,779.94,878.09,895.96,945.78,941.6,943.05,979.32,...,1107.67,1103.33,1152.33,1192,1251,1349,1344.67,1163.33,1139.67,1089.33
10,Research And Development Managers,AUST,102.53,111.32,118.87,121.3,119.18,116.34,104.01,94.67,...,127.33,128.67,138.67,134,140,142,148.33,134,135.67,132
11,Construction Managers,AUST,3283.45,3379.22,3636.21,4062.44,4361.84,4555.48,4363.69,4625.82,...,4045.33,4019,4265,4338.67,4400.67,4414.33,4303.33,3885,3929.33,4005.33
12,Engineering Managers,AUST,650.95,727,753.57,915.09,912.03,953.01,768.87,834.71,...,144.33,155,155.67,160.67,151,150.67,149,140.67,163.67,169.67
13,"Importers, Exporters And Wholesalers",AUST,41.14,44.19,52.07,52.74,51.36,49.19,50.67,54.62,...,29,26,28.33,24,25.67,28.67,32,29.67,29.67,30.33
14,Manufacturers,AUST,18.08,15.8,15.18,16.7,17.51,18.46,17.84,15.89,...,22.33,19.33,22,21.67,20.33,19.67,22,22.67,24.33,20.67
15,Production Managers,AUST,684.86,672.86,702.29,708.72,735.83,753.94,731.4,771.22,...,786,755.67,802,802,812,851,831,740.33,719.67,733.67
16,Supply And Distribution Managers,AUST,254.52,258.67,281.79,289.38,304.04,307.23,292.83,305.98,...,334,333.33,358,356.33,368.67,386,400.67,361,369.67,362.67
17,Child Care Centre Managers,AUST,64.18,66.44,72.06,74.8,69.42,70.99,67.34,75.77,...,166.33,173,174,170,164.33,160,154.33,145.33,152.33,147
18,Health And Welfare Services Managers,AUST,86.23,90.85,94.63,99.75,98.24,109.93,109.41,117.42,...,219,227.33,238,222,223.67,227.33,246,219.67,221,214.33
19,School Principals,AUST,26.13,34.44,36.61,36.89,37.68,47.27,60.6,69.58,...,37.33,36.33,46,58,78.67,87,82.33,59.33,42.33,67
20,Other Education Managers,AUST,45.25,37.51,39.32,41.47,49.64,52.95,58.78,66.31,...,59,54.33,57.33,58.67,66.33,66,67.33,54.67,63.67,59
21,Ict Managers,AUST,1041,1133.86,1234.43,1164.38,1232.43,1284.43,1383.86,1448.76,...,415.67,411.33,437,460.67,447.33,459,435,412,422,461.67
22,Commissioned Officers (Management),AUST,.,.,.,.,.,.,.,.,...,.,.,.,.,.,.,.,.,.,.
23,Other Specialist Managers,AUST,380.05,376.5,386.73,427.41,458.26,460.15,426.08,439.55,...,506.33,500,520.33,533.67,541.33,575.67,582.33,519.33,497,480
24,Cafe And Restaurant Managers,AUST,246.79,220.19,215.95,206.85,226.45,217.09,224.93,231.5,...,379.67,364.67,363.33,385,399.67,443.33,430.67,400,395.67,432
25,Caravan Park And Camping Ground Managers,AUST,17.07,15.74,18.74,16.41,16.12,17.76,18.84,19.86,...,11.33,8,9.67,10,11.67,9,10.67,9.33,9.67,6.67
26,Hotel And Motel Managers,AUST,233.41,225.99,253.85,247.51,242.46,236.65,246.87,287.77,...,259.33,252.67,255.33,272,285.67,314.67,310,287,295.33,283.67
27,Licensed Club Managers,AUST,38.17,36.53,36.94,37.65,39.63,37.27,34.79,37.2,...,78.33,73.33,86,86.33,88.67,84,89.33,76.67,80.67,82.33
28,Other Accommodation And Hospitality Managers,AUST,16.24,20.31,24.65,23.31,20.7,17.98,17.72,18.93,...,47.67,44.33,47,50,53.33,57.67,54.67,53.33,52.67,57.67
29,Retail Managers,AUST,2351.91,2315.6,2430.41,2484.09,2582.68,2628,2637.29,2817.6,...,2427,2441.67,2533.33,2609,2708,2819.33,2623.67,2240.67,2296,2374.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319,Other Construction And Mining Labourers,AUST,87.6,90.89,94.63,86.58,89.7,91.56,90.79,83.91,...,62,59.67,59.67,59.67,64.33,75.67,74.67,68.33,67.33,71.67
320,Food And Drink Factory Workers,AUST,392.32,395.44,394.73,376.87,374.15,406.82,445.87,488.27,...,99,96.67,91,84.67,89.67,103,102.33,86.33,77.33,76.33
321,"Meat Boners And Slicers, And Slaughterers",AUST,103.55,106.79,120.79,115.45,110.81,111.43,121.76,146.45,...,34,34.67,43.33,47.33,51.33,52,51,44.33,41,39.67
322,"Meat, Poultry And Seafood Process Workers",AUST,120.43,125.12,128.84,108.81,103.19,96.17,112.84,137.84,...,44.33,45.33,50.67,45.67,43.67,41.33,41,34,36,37.33
323,Packers,AUST,933.01,914.36,952.18,929.55,1005.08,1107.18,1241.05,1377.32,...,472.33,465.33,493,510,535.67,592,604.67,521.67,446.33,380.67
324,Product Assemblers,AUST,388.96,367.65,361.22,337.81,367.81,397.43,433.13,450.75,...,178.67,179,193,201.67,210.33,231.33,227,197.67,181,176.67
325,Metal Engineering Process Workers,AUST,26.1,23.81,26.84,23.48,21.86,21.6,21.01,20.96,...,17,15.33,16.33,13,13.33,11,12,10.67,12.33,14
326,Plastics And Rubber Factory Workers,AUST,2.69,2.36,3.67,4,3,3,4.36,7.36,...,2.33,2,3,2.67,2,0.33,0.67,1,1.33,0.67
327,Product Quality Controllers,AUST,206.57,216.17,242.51,238.05,236.05,223.98,217.32,220.48,...,632.33,598.33,613.67,640.67,667.67,696,668,606.33,620.67,641
328,Timber And Wood Process Workers,AUST,64.84,67.27,74.19,67.86,68.43,73.12,79.15,81.96,...,24,17,17.67,19,23.33,22.67,19.33,15.67,17.33,18.33
329,Other Factory Process Workers,AUST,1769.89,1707.31,1758.81,1696.05,1827.2,1936.58,2095.8,2279.91,...,521.67,509.67,551.67,557.33,551.33,576,544.33,457.67,408.33,399.67
330,Crop Farm Workers,AUST,639.02,595.69,523.05,383.74,359.41,336.69,339.02,374.74,...,123.67,116.67,142.33,144.33,141,141,145.33,156.67,163.67,162.33
331,Forestry And Logging Workers,AUST,128.27,133.93,215.29,292.67,336.03,288.74,205.03,151.74,...,33.33,43.33,46,45.67,41.67,37,30.67,25.33,28,28.33
332,Garden And Nursery Labourers,AUST,419.64,368.71,324.23,268.32,265.3,299.92,350.38,408.58,...,209,201.67,217.67,246.33,271.33,305.67,289.33,254.67,238.67,234
333,Livestock Farm Workers,AUST,191.98,182.58,190.43,178.45,191.88,199.96,214.27,215.55,...,65,57.67,61.33,60.33,57.33,61.67,64.67,63.67,61.33,60
334,Mixed Crop And Livestock Farm Workers,AUST,1321.1,1267.5,1203.19,1055.86,1094.15,1066.12,1081.15,1109.27,...,134.33,131,133,137.33,130.67,140,124,109,115.67,115.67
335,"Other Farm, Forestry And Garden Workers",AUST,98.11,88.01,72.99,60.1,59.88,68.77,85.94,98.96,...,95.33,85.67,88.67,81,84.33,91,98,91,94.67,92.33
336,Fast Food Cooks,AUST,262.24,247.86,253.86,237.4,241.95,271.21,295.47,334.57,...,61,63.33,66,61.67,65.67,63.33,65.33,56.67,54.33,43
337,Food Trades Assistants,AUST,98.91,104.32,101.94,100.13,98.84,106.46,113.44,125.62,...,60.33,62,68.67,61.33,56.33,58.67,61.33,51.33,45.33,40
338,Kitchenhands,AUST,2102.36,1980.9,1969.49,1782.06,1893.46,2072.59,2326.5,2529.2,...,720.33,703.33,771,800,882.33,957,944.67,811.33,778.67,786
339,Freight And Furniture Handlers,AUST,140.17,136.68,142.46,129.63,135.41,133.03,147.46,158.84,...,126,129.67,130,138,146.33,158.33,162,136.67,136.33,128.67
340,Shelf Fillers,AUST,131.02,133.1,134.41,123.79,129.05,142.1,169.38,206.48,...,20,12,14.33,22.33,34,49,51.33,38.67,28,33.33
341,Caretakers,AUST,124.01,133.58,132.06,130.91,135.03,153.05,148.99,151.76,...,102.33,106.67,103.67,109.67,104,110,103,87.33,83.67,83.33
342,Deck And Fishing Hands,AUST,142.45,143.43,133.76,115.72,106.72,102.72,106.76,108.17,...,18.67,18.67,19.33,21,26,24,24,22,25,22.33
343,Handypersons,AUST,534.5,503.48,513.57,472.12,483.01,496.84,503.32,552.83,...,452.33,432,440,439.67,457.33,506,507,449.33,430,430.33
344,Motor Vehicle Parts And Accessories Fitters,AUST,369.21,339.69,349.45,316.66,326.26,322.69,336.19,361.79,...,175,168.33,173.67,164.33,160,159.67,164.33,140.67,143.67,140.33
345,Printing Assistants And Table Workers,AUST,287.83,290.02,281.78,282.16,283.43,292.54,305.76,330,...,137.67,120.67,131,131,138.67,140.33,137.33,112.67,116.33,111
346,Recycling And Rubbish Collectors,AUST,22.36,21.79,21.91,18.72,14.29,12.22,15.48,17.48,...,8.33,9.67,9.33,9.33,10.67,12,13.33,11,11,9.33
347,Vending Machine Attendants,AUST,6.76,5.76,5.74,5.36,6.67,8,7.33,8.33,...,3.67,2,1.67,2,3,5,4,3,1,2
348,Other Miscellaneous Labourers,AUST,12095.7,11847.2,11970.9,11103.7,11226.7,11645.7,12484.1,13968.2,...,4023.67,3998.33,4173.33,4135,4163.33,4394.67,4313.67,3740.67,3521.67,3483.33

In [55]:
jobvac02 = merged_jobvac01.copy()

In [56]:
jobvac02

,OCCUPATIONS,STATES,2006-03-01 00:00:00,2006-04-01 00:00:00,2006-05-01 00:00:00,2006-06-01 00:00:00,2006-07-01 00:00:00,2006-08-01 00:00:00,2006-09-01 00:00:00,2006-10-01 00:00:00,...,2017-05-01 00:00:00,2017-06-01 00:00:00,2017-07-01 00:00:00,2017-08-01 00:00:00,2017-09-01 00:00:00,2017-10-01 00:00:00,2017-11-01 00:00:00,2017-12-01 00:00:00,2018-01-01 00:00:00,2018-02-01 00:00:00
0,Chief Executives And Managing Directors,AUST,158.85,160.57,180.53,207.43,214.49,212.53,197.01,216.38,...,309.33,322,337.67,329.33,339.67,345.33,359.33,298.67,302.33,277.67
1,General Managers,AUST,308.89,308.42,319.94,311.29,307.56,300.73,293.66,317.57,...,494.33,481.33,475,447.67,434.67,461.67,455.67,429,447.67,469
2,Legislators,AUST,.,.,.,.,.,.,.,.,...,.,.,.,.,.,.,.,.,.,.
3,Crop Farmers,AUST,25.74,33.15,32.84,22.86,15.84,16.12,15.38,16.69,...,8.33,9.67,12.67,16,14.67,13,11,11.67,12.67,10.67
4,Livestock Farmers,AUST,35.17,33.55,35.91,34.55,33.84,31.17,34.5,37.24,...,33.33,32.33,32.67,33,34,35.33,33.67,27.33,25.67,27.33
5,Advertising And Sales Managers,AUST,6397.5,6416.68,6649.76,6778.27,7164.54,7196.82,6934.29,6895.75,...,6385,6314.33,6632.67,6724,6762,6759.33,6424,5594.67,5732.33,5932
6,Corporate Services Managers,AUST,543.76,558.66,583.52,590.18,619.45,632.9,583.82,576.61,...,628.33,615,630,652.33,661.67,652,619.33,558.67,586.67,601
7,Finance Managers,AUST,1059.56,1110.33,1226.24,1267.71,1280.85,1244.69,1191.25,1256.6,...,866.33,864,876.67,836.33,839,875,866,780,790.67,828.67
8,Human Resource Managers,AUST,460.86,468.55,511.6,525.16,535.28,538.09,506.91,532.67,...,471.33,469,524,524,536,515.33,488.33,420.67,479,495
9,Policy And Planning Managers,AUST,788.41,779.94,878.09,895.96,945.78,941.6,943.05,979.32,...,1107.67,1103.33,1152.33,1192,1251,1349,1344.67,1163.33,1139.67,1089.33
10,Research And Development Managers,AUST,102.53,111.32,118.87,121.3,119.18,116.34,104.01,94.67,...,127.33,128.67,138.67,134,140,142,148.33,134,135.67,132
11,Construction Managers,AUST,3283.45,3379.22,3636.21,4062.44,4361.84,4555.48,4363.69,4625.82,...,4045.33,4019,4265,4338.67,4400.67,4414.33,4303.33,3885,3929.33,4005.33
12,Engineering Managers,AUST,650.95,727,753.57,915.09,912.03,953.01,768.87,834.71,...,144.33,155,155.67,160.67,151,150.67,149,140.67,163.67,169.67
13,"Importers, Exporters And Wholesalers",AUST,41.14,44.19,52.07,52.74,51.36,49.19,50.67,54.62,...,29,26,28.33,24,25.67,28.67,32,29.67,29.67,30.33
14,Manufacturers,AUST,18.08,15.8,15.18,16.7,17.51,18.46,17.84,15.89,...,22.33,19.33,22,21.67,20.33,19.67,22,22.67,24.33,20.67
15,Production Managers,AUST,684.86,672.86,702.29,708.72,735.83,753.94,731.4,771.22,...,786,755.67,802,802,812,851,831,740.33,719.67,733.67
16,Supply And Distribution Managers,AUST,254.52,258.67,281.79,289.38,304.04,307.23,292.83,305.98,...,334,333.33,358,356.33,368.67,386,400.67,361,369.67,362.67
17,Child Care Centre Managers,AUST,64.18,66.44,72.06,74.8,69.42,70.99,67.34,75.77,...,166.33,173,174,170,164.33,160,154.33,145.33,152.33,147
18,Health And Welfare Services Managers,AUST,86.23,90.85,94.63,99.75,98.24,109.93,109.41,117.42,...,219,227.33,238,222,223.67,227.33,246,219.67,221,214.33
19,School Principals,AUST,26.13,34.44,36.61,36.89,37.68,47.27,60.6,69.58,...,37.33,36.33,46,58,78.67,87,82.33,59.33,42.33,67
20,Other Education Managers,AUST,45.25,37.51,39.32,41.47,49.64,52.95,58.78,66.31,...,59,54.33,57.33,58.67,66.33,66,67.33,54.67,63.67,59
21,Ict Managers,AUST,1041,1133.86,1234.43,1164.38,1232.43,1284.43,1383.86,1448.76,...,415.67,411.33,437,460.67,447.33,459,435,412,422,461.67
22,Commissioned Officers (Management),AUST,.,.,.,.,.,.,.,.,...,.,.,.,.,.,.,.,.,.,.
23,Other Specialist Managers,AUST,380.05,376.5,386.73,427.41,458.26,460.15,426.08,439.55,...,506.33,500,520.33,533.67,541.33,575.67,582.33,519.33,497,480
24,Cafe And Restaurant Managers,AUST,246.79,220.19,215.95,206.85,226.45,217.09,224.93,231.5,...,379.67,364.67,363.33,385,399.67,443.33,430.67,400,395.67,432
25,Caravan Park And Camping Ground Managers,AUST,17.07,15.74,18.74,16.41,16.12,17.76,18.84,19.86,...,11.33,8,9.67,10,11.67,9,10.67,9.33,9.67,6.67
26,Hotel And Motel Managers,AUST,233.41,225.99,253.85,247.51,242.46,236.65,246.87,287.77,...,259.33,252.67,255.33,272,285.67,314.67,310,287,295.33,283.67
27,Licensed Club Managers,AUST,38.17,36.53,36.94,37.65,39.63,37.27,34.79,37.2,...,78.33,73.33,86,86.33,88.67,84,89.33,76.67,80.67,82.33
28,Other Accommodation And Hospitality Managers,AUST,16.24,20.31,24.65,23.31,20.7,17.98,17.72,18.93,...,47.67,44.33,47,50,53.33,57.67,54.67,53.33,52.67,57.67
29,Retail Managers,AUST,2351.91,2315.6,2430.41,2484.09,2582.68,2628,2637.29,2817.6,...,2427,2441.67,2533.33,2609,2708,2819.33,2623.67,2240.67,2296,2374.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319,Other Construction And Mining Labourers,AUST,87.6,90.89,94.63,86.58,89.7,91.56,90.79,83.91,...,62,59.67,59.67,59.67,64.33,75.67,74.67,68.33,67.33,71.67
320,Food And Drink Factory Workers,AUST,392.32,395.44,394.73,376.87,374.15,406.82,445.87,488.27,...,99,96.67,91,84.67,89.67,103,102.33,86.33,77.33,76.33
321,"Meat Boners And Slicers, And Slaughterers",AUST,103.55,106.79,120.79,115.45,110.81,111.43,121.76,146.45,...,34,34.67,43.33,47.33,51.33,52,51,44.33,41,39.67
322,"Meat, Poultry And Seafood Process Workers",AUST,120.43,125.12,128.84,108.81,103.19,96.17,112.84,137.84,...,44.33,45.33,50.67,45.67,43.67,41.33,41,34,36,37.33
323,Packers,AUST,933.01,914.36,952.18,929.55,1005.08,1107.18,1241.05,1377.32,...,472.33,465.33,493,510,535.67,592,604.67,521.67,446.33,380.67
324,Product Assemblers,AUST,388.96,367.65,361.22,337.81,367.81,397.43,433.13,450.75,...,178.67,179,193,201.67,210.33,231.33,227,197.67,181,176.67
325,Metal Engineering Process Workers,AUST,26.1,23.81,26.84,23.48,21.86,21.6,21.01,20.96,...,17,15.33,16.33,13,13.33,11,12,10.67,12.33,14
326,Plastics And Rubber Factory Workers,AUST,2.69,2.36,3.67,4,3,3,4.36,7.36,...,2.33,2,3,2.67,2,0.33,0.67,1,1.33,0.67
327,Product Quality Controllers,AUST,206.57,216.17,242.51,238.05,236.05,223.98,217.32,220.48,...,632.33,598.33,613.67,640.67,667.67,696,668,606.33,620.67,641
328,Timber And Wood Process Workers,AUST,64.84,67.27,74.19,67.86,68.43,73.12,79.15,81.96,...,24,17,17.67,19,23.33,22.67,19.33,15.67,17.33,18.33
329,Other Factory Process Workers,AUST,1769.89,1707.31,1758.81,1696.05,1827.2,1936.58,2095.8,2279.91,...,521.67,509.67,551.67,557.33,551.33,576,544.33,457.67,408.33,399.67
330,Crop Farm Workers,AUST,639.02,595.69,523.05,383.74,359.41,336.69,339.02,374.74,...,123.67,116.67,142.33,144.33,141,141,145.33,156.67,163.67,162.33
331,Forestry And Logging Workers,AUST,128.27,133.93,215.29,292.67,336.03,288.74,205.03,151.74,...,33.33,43.33,46,45.67,41.67,37,30.67,25.33,28,28.33
332,Garden And Nursery Labourers,AUST,419.64,368.71,324.23,268.32,265.3,299.92,350.38,408.58,...,209,201.67,217.67,246.33,271.33,305.67,289.33,254.67,238.67,234
333,Livestock Farm Workers,AUST,191.98,182.58,190.43,178.45,191.88,199.96,214.27,215.55,...,65,57.67,61.33,60.33,57.33,61.67,64.67,63.67,61.33,60
334,Mixed Crop And Livestock Farm Workers,AUST,1321.1,1267.5,1203.19,1055.86,1094.15,1066.12,1081.15,1109.27,...,134.33,131,133,137.33,130.67,140,124,109,115.67,115.67
335,"Other Farm, Forestry And Garden Workers",AUST,98.11,88.01,72.99,60.1,59.88,68.77,85.94,98.96,...,95.33,85.67,88.67,81,84.33,91,98,91,94.67,92.33
336,Fast Food Cooks,AUST,262.24,247.86,253.86,237.4,241.95,271.21,295.47,334.57,...,61,63.33,66,61.67,65.67,63.33,65.33,56.67,54.33,43
337,Food Trades Assistants,AUST,98.91,104.32,101.94,100.13,98.84,106.46,113.44,125.62,...,60.33,62,68.67,61.33,56.33,58.67,61.33,51.33,45.33,40
338,Kitchenhands,AUST,2102.36,1980.9,1969.49,1782.06,1893.46,2072.59,2326.5,2529.2,...,720.33,703.33,771,800,882.33,957,944.67,811.33,778.67,786
339,Freight And Furniture Handlers,AUST,140.17,136.68,142.46,129.63,135.41,133.03,147.46,158.84,...,126,129.67,130,138,146.33,158.33,162,136.67,136.33,128.67
340,Shelf Fillers,AUST,131.02,133.1,134.41,123.79,129.05,142.1,169.38,206.48,...,20,12,14.33,22.33,34,49,51.33,38.67,28,33.33
341,Caretakers,AUST,124.01,133.58,132.06,130.91,135.03,153.05,148.99,151.76,...,102.33,106.67,103.67,109.67,104,110,103,87.33,83.67,83.33
342,Deck And Fishing Hands,AUST,142.45,143.43,133.76,115.72,106.72,102.72,106.76,108.17,...,18.67,18.67,19.33,21,26,24,24,22,25,22.33
343,Handypersons,AUST,534.5,503.48,513.57,472.12,483.01,496.84,503.32,552.83,...,452.33,432,440,439.67,457.33,506,507,449.33,430,430.33
344,Motor Vehicle Parts And Accessories Fitters,AUST,369.21,339.69,349.45,316.66,326.26,322.69,336.19,361.79,...,175,168.33,173.67,164.33,160,159.67,164.33,140.67,143.67,140.33
345,Printing Assistants And Table Workers,AUST,287.83,290.02,281.78,282.16,283.43,292.54,305.76,330,...,137.67,120.67,131,131,138.67,140.33,137.33,112.67,116.33,111
346,Recycling And Rubbish Collectors,AUST,22.36,21.79,21.91,18.72,14.29,12.22,15.48,17.48,...,8.33,9.67,9.33,9.33,10.67,12,13.33,11,11,9.33
347,Vending Machine Attendants,AUST,6.76,5.76,5.74,5.36,6.67,8,7.33,8.33,...,3.67,2,1.67,2,3,5,4,3,1,2
348,Other Miscellaneous Labourers,AUST,12095.7,11847.2,11970.9,11103.7,11226.7,11645.7,12484.1,13968.2,...,4023.67,3998.33,4173.33,4135,4163.33,4394.67,4313.67,3740.67,3521.67,3483.33

### Reshape 1

In [57]:
index =['OCCUPATIONS','STATES']

In [58]:
multi_indexed_job = jobvac02.set_index(index)

In [59]:
multi_indexed_job.head(10)

,,2006-03-01 00:00:00,2006-04-01 00:00:00,2006-05-01 00:00:00,2006-06-01 00:00:00,2006-07-01 00:00:00,2006-08-01 00:00:00,2006-09-01 00:00:00,2006-10-01 00:00:00,2006-11-01 00:00:00,2006-12-01 00:00:00,...,2017-05-01 00:00:00,2017-06-01 00:00:00,2017-07-01 00:00:00,2017-08-01 00:00:00,2017-09-01 00:00:00,2017-10-01 00:00:00,2017-11-01 00:00:00,2017-12-01 00:00:00,2018-01-01 00:00:00,2018-02-01 00:00:00
OCCUPATIONS,STATES,,,,,,,,,,,,,,,,,,,,,
Chief Executives And Managing Directors,AUST,158.85,160.57,180.53,207.43,214.49,212.53,197.01,216.38,216.74,193.48,...,309.33,322,337.67,329.33,339.67,345.33,359.33,298.67,302.33,277.67
General Managers,AUST,308.89,308.42,319.94,311.29,307.56,300.73,293.66,317.57,322.08,293.76,...,494.33,481.33,475,447.67,434.67,461.67,455.67,429,447.67,469
Legislators,AUST,.,.,.,.,.,.,.,.,.,.,...,.,.,.,.,.,.,.,.,.,.
Crop Farmers,AUST,25.74,33.15,32.84,22.86,15.84,16.12,15.38,16.69,16.1,14.15,...,8.33,9.67,12.67,16,14.67,13,11,11.67,12.67,10.67
Livestock Farmers,AUST,35.17,33.55,35.91,34.55,33.84,31.17,34.5,37.24,37.55,30.5,...,33.33,32.33,32.67,33,34,35.33,33.67,27.33,25.67,27.33
Advertising And Sales Managers,AUST,6397.5,6416.68,6649.76,6778.27,7164.54,7196.82,6934.29,6895.75,6746.85,6096.33,...,6385,6314.33,6632.67,6724,6762,6759.33,6424,5594.67,5732.33,5932
Corporate Services Managers,AUST,543.76,558.66,583.52,590.18,619.45,632.9,583.82,576.61,541.83,524.28,...,628.33,615,630,652.33,661.67,652,619.33,558.67,586.67,601
Finance Managers,AUST,1059.56,1110.33,1226.24,1267.71,1280.85,1244.69,1191.25,1256.6,1314.39,1228.23,...,866.33,864,876.67,836.33,839,875,866,780,790.67,828.67
Human Resource Managers,AUST,460.86,468.55,511.6,525.16,535.28,538.09,506.91,532.67,524.79,468.35,...,471.33,469,524,524,536,515.33,488.33,420.67,479,495
Policy And Planning Managers,AUST,788.41,779.94,878.09,895.96,945.78,941.6,943.05,979.32,952.96,828.44,...,1107.67,1103.33,1152.33,1192,1251,1349,1344.67,1163.33,1139.67,1089.33

In [60]:
stacked_df1 = multi_indexed_job.stack(dropna=False)

In [61]:
stacked_df1.head(5)

OCCUPATIONS                              STATES
Chief Executives And Managing Directors  AUST    2006-03-01 00:00:00    158.85
                                                 2006-04-01 00:00:00    160.57
                                                 2006-05-01 00:00:00    180.53
                                                 2006-06-01 00:00:00    207.43
                                                 2006-07-01 00:00:00    214.49
dtype: object

In [62]:
stacked_df1 = stacked_df1.reset_index()

In [63]:
stacked_df1.head(5)

                               OCCUPATIONS STATES    level_2       0
0  Chief Executives And Managing Directors   AUST 2006-03-01  158.85
1  Chief Executives And Managing Directors   AUST 2006-04-01  160.57
2  Chief Executives And Managing Directors   AUST 2006-05-01  180.53
3  Chief Executives And Managing Directors   AUST 2006-06-01  207.43
4  Chief Executives And Managing Directors   AUST 2006-07-01  214.49

In [64]:
stacked_df1 = stacked_df1.rename(columns={'level_2' : 'Date', 0:'Vacancy'})

In [65]:
stacked_df1.head(5)

                               OCCUPATIONS STATES       Date Vacancy
0  Chief Executives And Managing Directors   AUST 2006-03-01  158.85
1  Chief Executives And Managing Directors   AUST 2006-04-01  160.57
2  Chief Executives And Managing Directors   AUST 2006-05-01  180.53
3  Chief Executives And Managing Directors   AUST 2006-06-01  207.43
4  Chief Executives And Managing Directors   AUST 2006-07-01  214.49

### Check Lenth and Null Value

In [67]:
jobvac03 = stacked_df1.copy()

In [68]:
len(jobvac03)

50256

In [69]:
len(jobvac03.dropna(axis = 0, how = 'any'))

50256

In [70]:
jobvac_clean = jobvac03[jobvac03.Vacancy!="."]

In [71]:
jobvac_clean[jobvac_clean.Vacancy=="."]

Empty DataFrame
Columns: [OCCUPATIONS, STATES, Date, Vacancy]
Index: []

In [72]:
jobvac_clean

                                   OCCUPATIONS STATES       Date  Vacancy
0      Chief Executives And Managing Directors   AUST 2006-03-01   158.85
1      Chief Executives And Managing Directors   AUST 2006-04-01   160.57
2      Chief Executives And Managing Directors   AUST 2006-05-01   180.53
3      Chief Executives And Managing Directors   AUST 2006-06-01   207.43
4      Chief Executives And Managing Directors   AUST 2006-07-01   214.49
5      Chief Executives And Managing Directors   AUST 2006-08-01   212.53
6      Chief Executives And Managing Directors   AUST 2006-09-01   197.01
7      Chief Executives And Managing Directors   AUST 2006-10-01   216.38
8      Chief Executives And Managing Directors   AUST 2006-11-01   216.74
9      Chief Executives And Managing Directors   AUST 2006-12-01   193.48
10     Chief Executives And Managing Directors   AUST 2007-01-01   184.95
11     Chief Executives And Managing Directors   AUST 2007-02-01   207.19
12     Chief Executives And Managing Directors   AUST 2007-03-01   241.38
13     Chief Executives And Managing Directors   AUST 2007-04-01   239.91
14     Chief Executives And Managing Directors   AUST 2007-05-01   247.08
15     Chief Executives And Managing Directors   AUST 2007-06-01    267.3
16     Chief Executives And Managing Directors   AUST 2007-07-01   307.31
17     Chief Executives And Managing Directors   AUST 2007-08-01   308.59
18     Chief Executives And Managing Directors   AUST 2007-09-01   303.71
19     Chief Executives And Managing Directors   AUST 2007-10-01   286.71
20     Chief Executives And Managing Directors   AUST 2007-11-01   285.76
21     Chief Executives And Managing Directors   AUST 2007-12-01   255.59
22     Chief Executives And Managing Directors   AUST 2008-01-01    240.2
23     Chief Executives And Managing Directors   AUST 2008-02-01   232.59
24     Chief Executives And Managing Directors   AUST 2008-03-01   267.29
25     Chief Executives And Managing Directors   AUST 2008-04-01    291.3
26     Chief Executives And Managing Directors   AUST 2008-05-01   310.76
27     Chief Executives And Managing Directors   AUST 2008-06-01   328.01
28     Chief Executives And Managing Directors   AUST 2008-07-01   341.58
29     Chief Executives And Managing Directors   AUST 2008-08-01   338.75
...                                        ...    ...        ...      ...
50226            Other Miscellaneous Labourers   AUST 2015-09-01     3050
50227            Other Miscellaneous Labourers   AUST 2015-10-01     3533
50228            Other Miscellaneous Labourers   AUST 2015-11-01  3864.33
50229            Other Miscellaneous Labourers   AUST 2015-12-01  3400.33
50230            Other Miscellaneous Labourers   AUST 2016-01-01  3048.67
50231            Other Miscellaneous Labourers   AUST 2016-02-01     3120
50232            Other Miscellaneous Labourers   AUST 2016-03-01  3466.67
50233            Other Miscellaneous Labourers   AUST 2016-04-01  3546.33
50234            Other Miscellaneous Labourers   AUST 2016-05-01     3494
50235            Other Miscellaneous Labourers   AUST 2016-06-01  3525.33
50236            Other Miscellaneous Labourers   AUST 2016-07-01     3612
50237            Other Miscellaneous Labourers   AUST 2016-08-01  3697.33
50238            Other Miscellaneous Labourers   AUST 2016-09-01  3931.67
50239            Other Miscellaneous Labourers   AUST 2016-10-01  4144.33
50240            Other Miscellaneous Labourers   AUST 2016-11-01     4263
50241            Other Miscellaneous Labourers   AUST 2016-12-01     3695
50242            Other Miscellaneous Labourers   AUST 2017-01-01  3433.67
50243            Other Miscellaneous Labourers   AUST 2017-02-01  3344.67
50244            Other Miscellaneous Labourers   AUST 2017-03-01     3901
50245            Other Miscellaneous Labourers   AUST 2017-04-01  3866.33
50246            Other Miscellaneous Labourers   AUST 2017-05-01  4023.67
50247            Other Miscellaneous Labourers   AUST 2017-06-01  3998.33
50248            Other Miscellaneous Labourers   AUST 2017-07-01  4173.33
50249            Other Miscellaneous Labourers   AUST 2017-08-01     4135
50250            Other Miscellaneous Labourers   AUST 2017-09-01  4163.33
50251            Other Miscellaneous Labourers   AUST 2017-10-01  4394.67
50252            Other Miscellaneous Labourers   AUST 2017-11-01  4313.67
50253            Other Miscellaneous Labourers   AUST 2017-12-01  3740.67
50254            Other Miscellaneous Labourers   AUST 2018-01-01  3521.67
50255            Other Miscellaneous Labourers   AUST 2018-02-01  3483.33

[49536 rows x 4 columns]

In [73]:
len(jobvac_clean)

49536

writer = pd.ExcelWriter('C:/Users/yiran/Google Drive/2018 S1/Cleaning Data/Material Data/VACANCY NEW AUST.xlsx')
jobvac_clean.to_excel(writer,sheet_name = 'Sheet1', index = False)
writer.save()

In [74]:
jobvac_clean.to_csv("C:/Users/yiran/Google Drive/2018 S1/Cleaning Data/Material Data/VACANCY NEW AUST.csv", index = False)